"""linkedin profile, review request, review result

Revision ID: 148b7c8f58e9
Revises: c2fd96b4c494
Create Date: 2026-10-05 10:13:22.328459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148b7c8f58e9'
down_revision: Union[str, Sequence[str], None] = 'c2fd96b4c494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('profile_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_profiles_candidate_profile_id'), 'linkedin_profiles', ['candidate_profile_id'], unique=True)
    op.create_table('linkedin_review_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('linkedin_profile_id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('profile_url_snapshot', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linkedin_profile_id'], ['linkedin_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_review_requests_candidate_profile_id'), 'linkedin_review_requests', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_linkedin_review_requests_linkedin_profile_id'), 'linkedin_review_requests', ['linkedin_profile_id'], unique=False)
    op.create_table('linkedin_review_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_request_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('improvements', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('recommendations', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('reviewer_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_request_id'], ['linkedin_review_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_review_results_review_request_id'), 'linkedin_review_results', ['review_request_id'], unique=True)
    # Hand-added: at most one non-COMPLETED review request per LinkedIn
    # profile -- the same partial-unique-index pattern as Phase 5's
    # uq_review_requests_active_per_resume, applied to the twin table.
    op.execute(
        "CREATE UNIQUE INDEX uq_linkedin_review_requests_active_per_profile "
        "ON linkedin_review_requests (linkedin_profile_id) WHERE status != 'COMPLETED'"
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping review_requests.
    # uq_review_requests_active_per_resume and skills.ix_skills_name_lower.
    # Both are false positives -- hand-written indexes (Phase 5 and
    # Phase 3 respectively) that the ORM models don't declare, so
    # autogenerate always sees them as "unexpected" and wants to remove
    # them. Left in place.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_linkedin_review_requests_active_per_profile")
    op.drop_index(op.f('ix_linkedin_review_results_review_request_id'), table_name='linkedin_review_results')
    op.drop_table('linkedin_review_results')
    op.drop_index(op.f('ix_linkedin_review_requests_linkedin_profile_id'), table_name='linkedin_review_requests')
    op.drop_index(op.f('ix_linkedin_review_requests_candidate_profile_id'), table_name='linkedin_review_requests')
    op.drop_table('linkedin_review_requests')
    op.drop_index(op.f('ix_linkedin_profiles_candidate_profile_id'), table_name='linkedin_profiles')
    op.drop_table('linkedin_profiles')
    # ### end Alembic commands ###
