"""credit transactions, interview slots, mock interviews, interview feedback

Revision ID: c1dccf2ee3d7
Revises: 148b7c8f58e9
Create Date: 2026-10-05 11:09:00.764485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1dccf2ee3d7'
down_revision: Union[str, Sequence[str], None] = '148b7c8f58e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interviewer_id', sa.UUID(), nullable=True),
    sa.Column('interview_type', sa.String(length=50), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('credit_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_candidate_profile_id'), 'credit_transactions', ['candidate_profile_id'], unique=False)
    op.create_table('mock_interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('credit_transaction_id', sa.UUID(), nullable=False),
    sa.Column('interview_type', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credit_transaction_id'], ['credit_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['interview_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_transaction_id'),
    sa.UniqueConstraint('slot_id')
    )
    op.create_index(op.f('ix_mock_interviews_candidate_profile_id'), 'mock_interviews', ['candidate_profile_id'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mock_interview_id', sa.UUID(), nullable=False),
    sa.Column('communication_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=False),
    sa.Column('answer_structure_score', sa.Integer(), nullable=False),
    sa.Column('professional_presentation_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('answer_structure_score BETWEEN 0 AND 10', name='ck_feedback_answer_structure_range'),
    sa.CheckConstraint('communication_score BETWEEN 0 AND 10', name='ck_feedback_communication_range'),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 10', name='ck_feedback_confidence_range'),
    sa.CheckConstraint('overall_score BETWEEN 0 AND 100', name='ck_feedback_overall_range'),
    sa.CheckConstraint('professional_presentation_score BETWEEN 0 AND 10', name='ck_feedback_professional_presentation_range'),
    sa.CheckConstraint('technical_score BETWEEN 0 AND 10', name='ck_feedback_technical_range'),
    sa.ForeignKeyConstraint(['mock_interview_id'], ['mock_interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mock_interview_id')
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping
    # uq_linkedin_review_requests_active_per_profile,
    # uq_review_requests_active_per_resume, and skills.ix_skills_name_lower.
    # All three are false positives -- hand-written indexes (Phases 3, 5,
    # 6) that the ORM models don't declare, so autogenerate always sees
    # them as "unexpected" and wants to remove them. Left in place, same
    # as every prior migration that hit this.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_feedback')
    op.drop_index(op.f('ix_mock_interviews_candidate_profile_id'), table_name='mock_interviews')
    op.drop_table('mock_interviews')
    op.drop_index(op.f('ix_credit_transactions_candidate_profile_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_table('interview_slots')
    # ### end Alembic commands ###
