"""candidate: profile, education, work experience, skills, career preferences

Revision ID: f305f06d4136
Revises: 41d65632bfa7
Create Date: 2026-10-05 07:17:29.650475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f305f06d4136'
down_revision: Union[str, Sequence[str], None] = '41d65632bfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Hand-added: case-insensitive uniqueness ("Python" and "python" are
    # the same skill). autogenerate can't express a functional index.
    op.execute("CREATE UNIQUE INDEX ix_skills_name_lower ON skills (lower(name))")
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('current_city', sa.String(length=100), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('degree', sa.String(length=150), nullable=True),
    sa.Column('specialisation', sa.String(length=150), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('career_goal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=True)
    op.create_table('candidate_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_profile_id', 'skill_id', name='uq_candidate_skill')
    )
    op.create_index(op.f('ix_candidate_skills_candidate_profile_id'), 'candidate_skills', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_skills_skill_id'), 'candidate_skills', ['skill_id'], unique=False)
    op.create_table('career_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('preferred_roles', sa.ARRAY(sa.String(length=100)), server_default='{}', nullable=False),
    sa.Column('preferred_locations', sa.ARRAY(sa.String(length=100)), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_preferences_candidate_profile_id'), 'career_preferences', ['candidate_profile_id'], unique=True)
    op.create_table('education_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=150), nullable=False),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('education_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_entries_candidate_profile_id'), 'education_entries', ['candidate_profile_id'], unique=False)
    op.create_table('work_experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experiences_candidate_profile_id'), 'work_experiences', ['candidate_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_experiences_candidate_profile_id'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_education_entries_candidate_profile_id'), table_name='education_entries')
    op.drop_table('education_entries')
    op.drop_index(op.f('ix_career_preferences_candidate_profile_id'), table_name='career_preferences')
    op.drop_table('career_preferences')
    op.drop_index(op.f('ix_candidate_skills_skill_id'), table_name='candidate_skills')
    op.drop_index(op.f('ix_candidate_skills_candidate_profile_id'), table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.execute("DROP INDEX IF EXISTS ix_skills_name_lower")
    op.drop_table('skills')
    # ### end Alembic commands ###
