from enum import StrEnum


class RoleName(StrEnum):
    CANDIDATE = "CANDIDATE"
    INTERVIEWER = "INTERVIEWER"
    CAREER_COACH = "CAREER_COACH"
    RECRUITER = "RECRUITER"
    ADMIN = "ADMIN"
    SUPER_ADMIN = "SUPER_ADMIN"


DEFAULT_REGISTRATION_ROLE = RoleName.CANDIDATE
